name: Merged to main repo workflow

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change directory to project
        run: cd small-talk

      - name: Install dependencies
        run: |
          npm init
          npm install

      - name: Lint with ESLint
        run: npm lint

      - name: Build Next.js app
        run: npm run build

#Will add deployment steps here when Vercel is set
