name: Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change directory to project
        uses: cd small-talk

      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm lint

      - name: Build Next.js app
        run: npm run build

#Will add deployment steps here when Vercel is set
